<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Serviços · Integração BI</title>
    <style>
        :root{--bg:#07110f;--panel:#0d1c18;--line:#26483f;--muted:#8ba79f;--text:#edf7f3;--green:#5dd6ad}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,sans-serif}.layout{min-height:100vh;display:grid;grid-template-columns:240px 1fr}.sidebar{position:sticky;top:0;height:100vh;padding:26px 18px;border-right:1px solid #1e3932;background:#091713}.brand{display:flex;align-items:center;gap:11px;padding:0 8px 28px}.mark{display:grid;place-items:center;width:38px;height:38px;border-radius:12px;background:#16372e;color:var(--green)}.brand strong{font-size:14px}.nav-label{padding:0 10px;margin:16px 0 7px;color:#5f8177;font-size:10px;text-transform:uppercase;letter-spacing:.13em}.nav-item{display:flex;align-items:center;gap:10px;padding:11px 12px;border-radius:10px;color:#91aea5;text-decoration:none;font-size:13px}.nav-item.active{background:#153129;color:#eafff7}.nav-item:hover{color:#fff;background:#10251f}.sidebar-foot{position:absolute;left:18px;right:18px;bottom:20px}.logout{width:100%;padding:10px;border:1px solid #2a4a41;border-radius:10px;background:transparent;color:#a9c3bb;cursor:pointer}.main{min-width:0;padding:34px clamp(22px,4vw,58px) 60px;background-image:radial-gradient(circle at 85% 0,#15382f 0,transparent 25%)}h1{margin:0 0 24px;font-size:25px;letter-spacing:-.04em}.panel{border:1px solid var(--line);border-radius:16px;overflow:hidden;background:var(--panel)}table{width:100%;border-collapse:collapse}th,td{padding:14px 16px;text-align:left;border-bottom:1px solid #19332c;font-size:12px}th{color:#789a90;font-size:10px;text-transform:uppercase;letter-spacing:.08em}.empty{padding:64px 20px;text-align:center;color:var(--muted)}.empty-icon{display:grid;place-items:center;width:44px;height:44px;margin:0 auto 14px;border:1px solid #31564c;border-radius:50%;color:var(--green)}.empty strong{display:block;margin-bottom:6px;color:#dceee8;font-size:14px}.empty span{font-size:12px}.status{display:inline-flex;padding:5px 9px;border-radius:999px;background:#192c27;color:#78978e}.action{padding:7px 10px;border:1px solid #2c4c43;border-radius:8px;background:transparent;color:#66847b}@media(max-width:760px){.layout{display:block}.sidebar{position:static;height:auto;border-right:0;border-bottom:1px solid var(--line)}.sidebar .nav-label,.sidebar-foot{display:none}.main{padding:25px 16px}.panel{overflow:auto}table{min-width:620px}}
        .toggle{width:34px;height:34px;flex:0 0 34px;padding:0;display:grid;place-items:center;border:1px solid #31584d;border-radius:50%;background:#10251f;color:#a8cec2;cursor:pointer;transition:background .2s,border-color .2s,color .2s,transform .25s}.toggle:hover{background:#18352d;border-color:#4c8b78;color:#e5fff7}.toggle svg{width:15px;height:15px;transition:transform .3s ease}.toggle.open svg{transform:rotate(180deg)}.detail-row td{padding:0;border-bottom:1px solid #26483f}.detail{max-height:0;overflow:hidden;background:#091713;transition:max-height .42s ease}.detail.open{max-height:720px}.detail-content{padding:22px 24px 26px;display:grid;grid-template-columns:1.2fr 1fr;gap:28px}.detail h3{margin:0 0 9px;font-size:13px}.detail p{margin:0;color:var(--muted);font-size:12px;line-height:1.65}.flow{display:flex;align-items:center;flex-wrap:wrap;gap:7px;margin-top:15px}.step{padding:7px 9px;border:1px solid #284a41;border-radius:8px;color:#b9d4cc;font-size:11px}.arrow{color:#52766b}.facts{display:grid;grid-template-columns:1fr 1fr;gap:9px}.fact{padding:11px;border:1px solid #213e36;border-radius:9px}.fact span{display:block;color:#698a80;font-size:9px;text-transform:uppercase;letter-spacing:.08em}.fact strong{display:block;margin-top:5px;font-size:11px}.fields{grid-column:1/-1}.chips{display:flex;flex-wrap:wrap;gap:6px}.chip{padding:5px 8px;border-radius:6px;background:#10251f;color:#8fb4a9;font:10px ui-monospace,SFMono-Regular,monospace}@media(max-width:760px){.detail-content{grid-template-columns:1fr}.fields{grid-column:auto}}
    </style>
</head>
<body><div class="layout">
    <aside class="sidebar"><div class="brand"><div class="mark">◆</div><strong>Integração BI</strong></div><div class="nav-label">Visão geral</div><a class="nav-item" href="{{ route('admin.dashboard') }}">◫ &nbsp; Painel</a><a class="nav-item active" href="{{ route('admin.services') }}">◇ &nbsp; Serviços</a><a class="nav-item" href="{{ route('docs') }}" target="_blank">↗ &nbsp; Swagger API</a><div class="sidebar-foot"><form method="POST" action="{{ route('admin.logout') }}">@csrf<button class="logout">Encerrar sessão</button></form></div></aside>
    <main class="main"><h1>Serviços</h1>
        @if(session('status'))<div style="margin-bottom:14px;padding:11px 14px;border:1px solid #34715f;border-radius:10px;background:#123128;color:#8ce8c6;font-size:12px">{{ session('status') }}</div>@endif
        <section class="panel"><table><thead><tr><th>Serviço</th><th>Status</th><th>Agenda</th><th>Última execução</th><th>Ações</th></tr></thead><tbody>
            @forelse($services as $service)
                @php($lastRun = $service->runs->first())
                <tr><td><strong>{{ $service->name }}</strong><br><span style="color:var(--muted)">Empresa {{ $service->empresa_codigo }} · {{ ucfirst($service->category) }}</span></td>
                    <td><span class="status" style="{{ $service->active ? 'background:#173c31;color:#7ce5bf' : '' }}">{{ $service->active ? 'Ativo' : 'Pausado' }}</span></td>
                    <td>A cada {{ $service->frequency_minutes }} min<br><span style="color:var(--muted)">{{ $service->lookback_days }} dias por consulta</span></td>
                    <td>@if($lastRun)<strong>{{ $lastRun->status === 'success' ? 'Concluída' : ($lastRun->status === 'failed' ? 'Falhou' : 'Executando') }}</strong><br><span style="color:var(--muted)">{{ optional($lastRun->started_at)->format('d/m/Y H:i') }} · {{ $lastRun->received }} recebidos</span>@else<span style="color:var(--muted)">Nunca executado</span>@endif</td>
                    <td><div style="display:flex;gap:7px;align-items:center"><form method="POST" action="{{ route('admin.services.run', $service) }}">@csrf<button class="action" type="submit" style="cursor:pointer;color:#bfe0d6">Executar</button></form>
                        @if($service->active)<form method="POST" action="{{ route('admin.services.pause', $service) }}">@csrf<button class="action" type="submit" style="cursor:pointer">Pausar</button></form>
                        @else<form method="POST" action="{{ route('admin.services.resume', $service) }}">@csrf<button class="action" type="submit" style="cursor:pointer">Ativar</button></form>@endif
                        <button class="toggle" type="button" data-detail="service-{{ $service->id }}" title="Ver detalhes" aria-label="Ver detalhes"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m6 9 6 6 6-6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></button></div></td></tr>
                <tr class="detail-row"><td colspan="5"><div class="detail" id="service-{{ $service->id }}"><div class="detail-content">
                    <div><h3>Como funciona</h3><p>Consulta os títulos a receber da empresa {{ $service->empresa_codigo }} em uma janela móvel de {{ $service->lookback_days }} dias. Registros novos são inseridos e títulos existentes são atualizados pela combinação de empresa e <code>tituloCodigo</code>.</p>
                        <div class="flow"><span class="step">Agendador</span><span class="arrow">→</span><span class="step">Fila financeira</span><span class="arrow">→</span><span class="step">WebPosto</span><span class="arrow">→</span><span class="step">titulos_receber</span></div></div>
                    <div class="facts"><div class="fact"><span>Último acionamento</span><strong>{{ optional($service->last_started_at)->format('d/m/Y H:i:s') ?: 'Nunca' }}</strong></div><div class="fact"><span>Última conclusão</span><strong>{{ optional($service->last_completed_at)->format('d/m/Y H:i:s') ?: 'Nunca' }}</strong></div><div class="fact"><span>Próxima execução</span><strong>{{ $service->active ? (optional($service->next_run_at)->format('d/m/Y H:i:s') ?: 'Aguardando agenda') : 'Serviço pausado' }}</strong></div><div class="fact"><span>Destino</span><strong>webposto.titulos_receber</strong></div></div>
                    <div class="fields"><h3>Campos de controle no banco de integração</h3><div class="chips">@foreach(['name','slug','category','resource','empresa_codigo','frequency_minutes','lookback_days','active','last_started_at','last_completed_at','next_run_at','last_error'] as $field)<span class="chip">{{ $field }}</span>@endforeach</div></div>
                    <div class="fields"><h3>Histórico de execução</h3><div class="chips">@foreach(['status','period_start','period_end','received','inserted','updated','unchanged','skipped','error','started_at','finished_at'] as $field)<span class="chip">{{ $field }}</span>@endforeach</div></div>
                </div></div></td></tr>
            @empty
                <tr><td colspan="5"><div class="empty"><div class="empty-icon">◇</div><strong>Nenhum serviço configurado</strong></div></td></tr>
            @endforelse
        </tbody></table></section>
    </main>
</div><script>document.querySelectorAll('.toggle').forEach(button=>button.addEventListener('click',()=>{const panel=document.getElementById(button.dataset.detail);const open=panel.classList.toggle('open');button.classList.toggle('open',open);button.setAttribute('aria-expanded',open?'true':'false')}));</script></body></html>
