<?php

namespace App\Services\WebPosto;

use App\Models\WebPostoCredential;

class WebPostoNewRecordsResourceCatalog
{
    /** @return array<string, array<string, mixed>> */
    public function all(): array
    {
        return [
            'produto_grupos' => [
                'endpoint' => '/INTEGRACAO/GRUPO',
                'table' => 'produto_grupos',
                'key' => 'grupoCodigo',
                'natural_keys' => ['grupoCodigo'],
                'mode' => 'snapshot_new',
                'query_company_field' => 'empresaCodigo',
                'query' => [],
                'importer' => ProdutoGrupoImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'produto_subgrupos' => [
                'endpoint' => '/INTEGRACAO/CONSULTAR_SUB_GRUPO_REDE',
                'table' => 'produto_subgrupos',
                'key' => 'subGrupoCodigo',
                'natural_keys' => ['grupoCodigo', 'subGrupoCodigo'],
                'mode' => 'snapshot_new',
                'cursor' => ['single_page' => true, 'direct_list' => true],
                'query' => [],
                'importer' => ProdutoSubgrupoImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'produtos' => [
                'endpoint' => '/INTEGRACAO/PRODUTO',
                'table' => 'produtos',
                'key' => 'produtoCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [],
                'importer' => ProdutoImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'produto_empresas' => [
                'endpoint' => '/INTEGRACAO/PRODUTO_EMPRESA',
                'table' => 'produto_empresas',
                'key' => 'produtoCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [],
                'importer' => ProdutoEmpresaImporter::class,
                'updated_field' => 'ultimaAlteracao',
            ],
            'estoque_periodos' => [
                'endpoint' => '/INTEGRACAO/ESTOQUE_PERIODO',
                'table' => 'estoque_periodos',
                'key' => 'codigo',
                'company_field' => 'codigoUnidadeNegocio',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => EstoquePeriodoImporter::class,
                'updated_field' => 'dataMovimento',
            ],
            'produto_lmc_lmp' => [
                'endpoint' => '/INTEGRACAO/PRODUTO_LMC_LMP',
                'table' => 'produto_lmc_lmp',
                'key' => 'produtoLmcCodigo',
                'natural_keys' => ['produtoLmcCodigo'],
                'mode' => 'snapshot_new',
                'cursor' => ['single_page' => true, 'direct_list' => true],
                'query_company_field' => 'empresaCodigo',
                'query' => [],
                'importer' => ProdutoLmcLmpImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'lmcs' => [
                'endpoint' => '/INTEGRACAO/LMC',
                'table' => 'lmcs',
                'key' => 'lmcCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => LmcImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
                'reconciliation_updated_period' => true,
            ],
            'bombas' => [
                'endpoint' => '/INTEGRACAO/BOMBA',
                'table' => 'bombas',
                'key' => 'bombaCodigo',
                'natural_keys' => ['bombaCodigo'],
                'mode' => 'snapshot_new',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'cursor' => ['single_page' => true],
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                    'limite' => 1000,
                ],
                'importer' => BombaImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'bicos' => [
                'endpoint' => '/INTEGRACAO/BICO',
                'table' => 'bicos',
                'key' => 'bicoCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => BicoImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'tanques' => [
                'endpoint' => '/INTEGRACAO/TANQUE',
                'table' => 'tanques',
                'key' => 'tanqueCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => TanqueImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'funcionario_funcoes' => [
                'endpoint' => '/INTEGRACAO/FUNCOES',
                'table' => 'funcionario_funcoes',
                'key' => 'funcaoCodigo',
                'natural_keys' => ['funcaoCodigo'],
                'mode' => 'snapshot_new',
                'company_scoped' => false,
                'query' => [],
                'importer' => FuncionarioFuncaoImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'funcionarios' => [
                'endpoint' => '/INTEGRACAO/FUNCIONARIO',
                'table' => 'funcionarios',
                'key' => 'funcionarioCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => FuncionarioImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'vales_funcionario' => [
                'endpoint' => '/INTEGRACAO/VALE_FUNCIONARIO',
                'table' => 'vales_funcionario',
                'key' => 'funcionarioCreditoCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => ValeFuncionarioImporter::class,
                'updated_field' => 'data',
            ],
            'caixas' => [
                'endpoint' => '/INTEGRACAO/CAIXA',
                'table' => 'caixas',
                'key' => 'caixaCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => CaixaImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
                'reconciliation_updated_period' => true,
            ],
            'caixas_apresentados' => [
                'endpoint' => '/INTEGRACAO/CAIXA_APRESENTADO',
                'table' => 'caixas_apresentados',
                'key' => 'caixaCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => CaixaApresentadoImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
                'reconciliation_updated_period' => true,
            ],
            'fornecedores' => [
                'endpoint' => '/INTEGRACAO/FORNECEDOR',
                'table' => 'fornecedores',
                'key' => 'fornecedorCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [],
                'importer' => FornecedorImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'compras' => [
                'endpoint' => '/INTEGRACAO/COMPRA',
                'table' => 'compras',
                'key' => 'compraCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => CompraImporter::class,
                'updated_field' => 'dataMovimento',
            ],
            'compra_itens' => [
                'endpoint' => '/INTEGRACAO/COMPRA_ITEM',
                'table' => 'compra_itens',
                'key' => 'compraCodigo',
                'natural_keys' => ['compraCodigo', 'sequencialItem'],
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => CompraItemImporter::class,
                'updated_field' => 'dataMovimento',
            ],
            'titulos_pagar' => [
                'endpoint' => '/INTEGRACAO/TITULO_PAGAR',
                'table' => 'titulos_pagar',
                'key' => 'tituloPagarCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => TituloPagarImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
                'reconciliation_updated_period' => true,
            ],
            'cliente_grupos' => [
                'endpoint' => '/INTEGRACAO/GRUPO_CLIENTE',
                'table' => 'cliente_grupos',
                'key' => 'grupoCodigo',
                'natural_keys' => ['grupoCodigo'],
                'mode' => 'snapshot_new',
                'query_company_field' => 'empresaCodigo',
                'query' => [],
                'importer' => ClienteGrupoImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'clientes' => [
                'endpoint' => '/INTEGRACAO/CLIENTE',
                'table' => 'clientes',
                'key' => 'clienteCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [],
                'importer' => ClienteImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'cliente_empresas' => [
                'endpoint' => '/INTEGRACAO/CLIENTE_EMPRESA',
                'table' => 'cliente_empresas',
                'key' => 'codigo',
                'natural_keys' => ['clienteCodigo'],
                'query_company_field' => 'empresaCodigo',
                'limit' => 200,
                'query' => [],
                'importer' => ClienteEmpresaImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'formas_pagamento' => [
                'endpoint' => '/INTEGRACAO/FORMA_PAGAMENTO',
                'table' => 'formas_pagamento',
                'key' => 'formaPagamentoCodigo',
                'natural_keys' => ['formaPagamentoCodigo'],
                'mode' => 'snapshot_new',
                'query_company_field' => 'empresaCodigo',
                'query' => [],
                'importer' => FormaPagamentoImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'pdvs' => [
                'endpoint' => '/INTEGRACAO/PDV',
                'table' => 'pdvs',
                'key' => 'pdvCodigo',
                'natural_keys' => ['pdvCodigo'],
                'mode' => 'snapshot_new',
                'query_company_field' => 'empresaCodigo',
                'query' => [],
                'importer' => PdvImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'vendas' => [
                'endpoint' => '/INTEGRACAO/VENDA',
                'table' => 'vendas',
                'key' => 'vendaCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => VendaImporter::class,
                'updated_field' => 'dataHora',
            ],
            'venda_formas_pagamento' => [
                'endpoint' => '/INTEGRACAO/VENDA_FORMA_PAGAMENTO',
                'table' => 'venda_formas_pagamento',
                'key' => 'codigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => VendaFormaPagamentoImporter::class,
                'updated_field' => 'dataMovimento',
            ],
            'titulos_receber' => [
                'endpoint' => '/INTEGRACAO/TITULO_RECEBER',
                'table' => 'titulos_receber',
                'key' => 'tituloCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => TituloReceberImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
                'reconciliation_updated_period' => true,
            ],
            'contas_bancarias' => [
                'endpoint' => '/INTEGRACAO/CONTA',
                'table' => 'contas_bancarias',
                'key' => 'contaCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => ContaBancariaImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'movimentos_conta' => [
                'endpoint' => '/INTEGRACAO/MOVIMENTO_CONTA',
                'table' => 'movimentos_conta',
                'key' => 'movimentoContaCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => MovimentoContaImporter::class,
                'updated_field' => 'dataMovimento',
            ],
            'venda_itens' => [
                'endpoint' => '/INTEGRACAO/VENDA_ITEM',
                'table' => 'venda_itens',
                'key' => 'vendaItemCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => VendaItemImporter::class,
                'updated_field' => 'dataMovimento',
            ],
            'abastecimentos' => [
                'endpoint' => '/INTEGRACAO/ABASTECIMENTO',
                'table' => 'abastecimentos',
                'key' => 'abastecimentoCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => AbastecimentoImporter::class,
                'updated_field' => 'dataHoraAbastecimento',
            ],
            'administradoras' => [
                'endpoint' => '/INTEGRACAO/ADMINISTRADORA',
                'table' => 'administradoras',
                'key' => 'administradoraCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [],
                'importer' => AdministradoraImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'centros_custo' => [
                'endpoint' => '/INTEGRACAO/CENTRO_CUSTO',
                'table' => 'centros_custo',
                'key' => 'centroCustoCodigo',
                'natural_keys' => ['centroCustoCodigo'],
                'mode' => 'snapshot_new',
                'company_scoped' => false,
                'cursor' => ['single_page' => true],
                'query' => [],
                'importer' => CentroCustoImporter::class,
                'updated_field' => 'dataHoraAtualizacao',
            ],
            'cartoes' => [
                'endpoint' => '/INTEGRACAO/CARTAO',
                'table' => 'cartoes',
                'key' => 'cartaoCodigo',
                'query_company_field' => 'empresaCodigo',
                'limit' => 1000,
                'query' => [
                    'dataInicial' => '2000-01-01',
                    'dataFinal' => now()->toDateString(),
                ],
                'importer' => CartaoImporter::class,
                'updated_field' => 'dataMovimento',
            ],
        ];
    }

    /** @return array<string, mixed> */
    public function get(string $resource, ?string $base = null): array
    {
        $definition = $this->all()[$resource] ?? throw new \InvalidArgumentException(
            "Recurso {$resource} nao esta liberado para sincronizacao incremental.",
        );

        if ($base !== null && $base !== WebPostoCredential::BASE_CHIMBA && isset($definition['query']['dataInicial'])) {
            $definition['query']['dataInicial'] = max(
                $definition['query']['dataInicial'],
                (string) config('integration.webposto.recent_base_initial_date'),
            );
        }

        return $definition;
    }
}
