<?php

namespace App\Services\ClickHouse;

use InvalidArgumentException;

/**
 * Fonte unica de verdade das tabelas MySQL (webposto) replicadas no ClickHouse.
 * Porta de App\Console\Commands\ClickHouseSyncCommand::TABLE_DEFS do projeto
 * Back-end-bi, mantendo o mesmo subconjunto curado de colunas (nao e copia 1:1
 * do schema MySQL - colunas tributarias pesadas foram deliberadamente excluidas
 * na origem).
 */
class ClickHouseTableCatalog
{
    public const HEAVY_QUEUE = 'clickhouse-heavy';

    /**
     * Tabelas fato pesadas isoladas numa fila propria, para que o volume alto
     * do Chimba nao atrase o sync das ~24 tabelas pequenas atras delas na
     * mesma fila.
     */
    private const HEAVY_TABLES = ['venda_itens', 'abastecimentos', 'vendas', 'compra_itens'];

    /**
     * @return array<string, array<string, mixed>>
     */
    public function all(): array
    {
        $defs = self::TABLE_DEFS;

        foreach ($defs as $table => $definition) {
            $defs[$table]['cursor'] = self::BUSINESS_CURSORS[$table] ?? ['col' => 'codigo', 'key' => 'codigo', 'empresa_col' => null];
            $defs[$table]['parent_join'] = self::PARENT_JOINS[$table] ?? null;
            $defs[$table]['queue'] = in_array($table, self::HEAVY_TABLES, true) ? self::HEAVY_QUEUE : 'default';
        }

        return $defs;
    }

    /**
     * @return array<string, mixed>
     */
    public function get(string $table): array
    {
        return $this->all()[$table] ?? throw new InvalidArgumentException("Tabela ClickHouse desconhecida: {$table}");
    }

    /**
     * @return array<int, string>
     */
    public function tables(): array
    {
        return array_keys(self::TABLE_DEFS);
    }

    /**
     * empresaCol usa o alias da tabela quando o SELECT precisa de JOIN
     * (venda_itens/compra_itens); os outros SELECTs de tabela unica nao usam alias.
     */
    private const BUSINESS_CURSORS = [
        'venda_itens' => ['col' => 'vi.vendaItemCodigo', 'key' => 'vendaItemCodigo', 'empresa_col' => 'vi.empresaCodigo'],
        'abastecimentos' => ['col' => 'abastecimentoCodigo', 'key' => 'abastecimentoCodigo', 'empresa_col' => 'empresaCodigo'],
        'vendas' => ['col' => 'vendaCodigo', 'key' => 'vendaCodigo', 'empresa_col' => 'empresaCodigo'],
        // 'codigo' em compra_itens repete pra todos os itens da mesma compra
        // (nao e por-linha como vendaItemCodigo em venda_itens) - usar 'id'
        // (unico de verdade) evita perder linha quando um lote corta no meio
        // de um grupo de codigo duplicado.
        'compra_itens' => ['col' => 'ci.id', 'key' => 'id', 'empresa_col' => 'ci.empresaCodigo'],
        'compras' => ['col' => 'compraCodigo', 'key' => 'compraCodigo', 'empresa_col' => 'empresaCodigo'],
        'bicos' => ['col' => 'bicoCodigo', 'key' => 'bicoCodigo', 'empresa_col' => 'empresaCodigo'],
        'bombas' => ['col' => 'bombaCodigo', 'key' => 'bombaCodigo', 'empresa_col' => 'empresaCodigo'],
        'tanques' => ['col' => 'tanqueCodigo', 'key' => 'tanqueCodigo', 'empresa_col' => 'empresaCodigo'],
        'empresas' => ['col' => 'empresaCodigo', 'key' => 'empresaCodigo', 'empresa_col' => null],
        'funcionarios' => ['col' => 'funcionarioCodigo', 'key' => 'funcionarioCodigo', 'empresa_col' => null],
        // produtoCodigo/fornecedorCodigo NAO sao globalmente unicos - cada
        // empresa tem seu proprio catalogo e os codigos se repetem entre
        // empresas (confirmado: 16854 linhas / so 8598 produtoCodigo
        // distintos). Sem o empresa_col a paginacao keyset perde linha toda
        // vez que um lote corta no meio de um grupo de codigo duplicado -
        // mesma classe de bug encontrada em compra_itens.
        'produtos' => ['col' => 'produtoCodigo', 'key' => 'produtoCodigo', 'empresa_col' => 'empresaCodigo'],
        'fornecedores' => ['col' => 'fornecedorCodigo', 'key' => 'fornecedorCodigo', 'empresa_col' => 'empresaCodigo'],
        'clientes' => ['col' => 'clienteCodigo', 'key' => 'clienteCodigo', 'empresa_col' => 'empresaCodigo'],
        // mesmo caso de produtos/fornecedores: 'codigo' aqui e o produtoCodigo
        // e se repete entre empresas (16728 linhas / so 8472 codigos distintos).
        'produto_empresas' => ['col' => 'codigo', 'key' => 'codigo', 'empresa_col' => 'empresaCodigo'],
    ];

    /**
     * Backfill estrutural via LEFT JOIN com a tabela pai (nao e regra de negocio
     * por empresa/cliente - venda_itens/compra_itens do webposto nao carregam
     * clienteCodigo/fornecedorCodigo de forma confiavel, so a venda/compra pai tem).
     */
    private const PARENT_JOINS = [
        'venda_itens' => [
            'parent_table' => 'vendas',
            'parent_alias' => 'v',
            'child_alias' => 'vi',
            'on' => ['vendaCodigo', 'empresaCodigo'],
            'backfill_column' => 'clienteCodigo',
            'backfill_source' => 'v.clienteCodigo',
        ],
        'compra_itens' => [
            'parent_table' => 'compras',
            'parent_alias' => 'c',
            'child_alias' => 'ci',
            'on' => ['compraCodigo', 'empresaCodigo'],
            'backfill_column' => 'fornecedorCodigo',
            'backfill_source' => 'c.fornecedorCodigo',
        ],
    ];

    public const TABLE_DEFS = [
        'venda_itens' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'vendaCodigo' => 'UInt64',
                'vendaItemCodigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'produtoCodigo' => 'UInt64',
                'funcionarioCodigo' => 'UInt64',
                'clienteCodigo' => 'UInt64',
                'bicoCodigo' => 'UInt64',
                'tanqueCodigo' => 'UInt64',
                'produtoLmcCodigo' => 'UInt64',
                'dataMovimento' => 'DateTime',
                'quantidade' => 'Decimal(18,4)',
                'precoVenda' => 'Decimal(18,4)',
                'precoCusto' => 'Decimal(18,4)',
                'totalVenda' => 'Decimal(18,4)',
                'totalCusto' => 'Decimal(18,4)',
                'totalDesconto' => 'Decimal(18,4)',
                'totalAcrescimo' => 'Decimal(18,4)',
                'cfop' => 'String',
                'cst' => 'String',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(empresaCodigo, dataMovimento, produtoCodigo)',
            'partition_by' => 'toYYYYMM(dataMovimento)',
            'date_column' => 'dataMovimento',
        ],
        'abastecimentos' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'abastecimentoCodigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'codigoBico' => 'UInt64',
                'codigoFrentista' => 'UInt64',
                'codigoProduto' => 'String',
                'dataFiscal' => 'DateTime',
                'dataHoraAbastecimento' => 'DateTime',
                'quantidade' => 'Decimal(18,4)',
                'valorUnitario' => 'Decimal(18,4)',
                'valorTotal' => 'Decimal(18,4)',
                'encerrante' => 'Decimal(18,4)',
                'afericao' => 'UInt8',
                'precoCadastro' => 'Decimal(18,4)',
                'vendaItemCodigo' => 'UInt64',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(empresaCodigo, dataHoraAbastecimento)',
            'partition_by' => 'toYYYYMM(dataHoraAbastecimento)',
            'date_column' => 'dataHoraAbastecimento',
        ],
        'vendas' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'vendaCodigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'funcionarioCodigo' => 'UInt64',
                'clienteCodigo' => 'UInt64',
                'dataHora' => 'DateTime',
                'totalVenda' => 'Decimal(18,4)',
                'caixaCodigo' => 'UInt64',
                'placaVeiculo' => 'String',
                'modeloDocumento' => 'String',
                'notaNumero' => 'String',
                'cancelada' => 'String',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(empresaCodigo, dataHora)',
            'partition_by' => 'toYYYYMM(dataHora)',
            'date_column' => 'dataHora',
        ],
        'cartoes' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'administradoraCodigo' => 'UInt64',
                'adiministradoraDescricao' => 'String',
                'cartaoCodigo' => 'UInt64',
                'vendaCodigo' => 'UInt64',
                'dataMovimento' => 'DateTime',
                'dataFiscal' => 'DateTime',
                'dataPagamento' => 'DateTime',
                'vencimento' => 'DateTime',
                'valor' => 'Decimal(18,4)',
                'taxaPercentual' => 'Decimal(18,4)',
                'parcela' => 'UInt64',
                'pendente' => 'UInt8',
                'clienteCpfCnpj' => 'String',
                'clienteRazao' => 'String',
                'nsu' => 'String',
                'codigoBandeira' => 'String',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(empresaCodigo, dataMovimento)',
            'partition_by' => 'toYYYYMM(dataMovimento)',
            'date_column' => 'dataMovimento',
        ],
        'titulos_receber' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'clienteCodigo' => 'UInt64',
                'tituloCodigo' => 'UInt64',
                'tituloNumero' => 'UInt64',
                'duplicataCodigo' => 'UInt64',
                'vendaCodigo' => 'UInt64',
                'dataMovimento' => 'DateTime',
                'dataVencimento' => 'DateTime',
                'dataPagamento' => 'DateTime',
                'dataHoraAtualizacao' => 'DateTime',
                'valor' => 'Decimal(18,4)',
                'pendente' => 'UInt8',
                'convertido' => 'UInt8',
                'tipo' => 'String',
                'documento' => 'String',
                'nomeCliente' => 'String',
                'cpfCnpjCliente' => 'String',
                'planoContaGerencialCodigo' => 'UInt64',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(empresaCodigo, dataVencimento)',
            'partition_by' => 'toYYYYMM(dataVencimento)',
            'date_column' => 'dataMovimento',
        ],
        'titulos_pagar' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'fornecedorCodigo' => 'UInt64',
                'tituloPagarCodigo' => 'UInt64',
                'notaEntradaCodigo' => 'UInt64',
                'centroCustoCodigo' => 'UInt64',
                'planoContaGerencialCodigo' => 'UInt64',
                'dataMovimento' => 'DateTime',
                'vencimento' => 'DateTime',
                'dataPagamento' => 'DateTime',
                'dataHoraAtualizacao' => 'DateTime',
                'valor' => 'Decimal(18,4)',
                'valorPago' => 'Decimal(18,4)',
                'acrescimo' => 'Decimal(18,4)',
                'desconto' => 'Decimal(18,4)',
                'dinheiro' => 'Decimal(18,4)',
                'cheque' => 'Decimal(18,4)',
                'cartao' => 'Decimal(18,4)',
                'adiantamento' => 'Decimal(18,4)',
                'troco' => 'Decimal(18,4)',
                'parcela' => 'UInt64',
                'quantidadeParcelas' => 'UInt64',
                'autorizado' => 'UInt8',
                'situacao' => 'String',
                'tipo' => 'String',
                'tipoLancamento' => 'String',
                'tipoTributo' => 'String',
                'descricao' => 'String',
                'nomeFornecedor' => 'String',
                'cpfCnpjFornecedor' => 'String',
                'numeroTitulo' => 'String',
                'planoContaGerencialDescricao' => 'String',
                'planoContaGerencialNivel' => 'String',
                'centroCustoDescricao' => 'String',
                'observacao' => 'String',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(empresaCodigo, vencimento)',
            'partition_by' => 'toYYYYMM(vencimento)',
            'date_column' => 'dataMovimento',
        ],
        'lmcs' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'lmcCodigo' => 'UInt64',
                'produtoLmcCodigo' => 'UInt64',
                'dataMovimento' => 'DateTime',
                'dataHoraAtualizacao' => 'DateTime',
                'abertura' => 'Decimal(18,4)',
                'entrada' => 'Decimal(18,4)',
                'saida' => 'Decimal(18,4)',
                'fechamento' => 'Decimal(18,4)',
                'perdaSobra' => 'Decimal(18,4)',
                'disponivel' => 'Decimal(18,4)',
                'escritural' => 'Decimal(18,4)',
                'saldo' => 'Decimal(18,4)',
                'precoCusto' => 'Decimal(18,4)',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(empresaCodigo, dataMovimento, produtoLmcCodigo)',
            'partition_by' => 'toYYYYMM(dataMovimento)',
            'date_column' => 'dataMovimento',
        ],
        'venda_formas_pagamento' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'vendaCodigo' => 'UInt64',
                'formaPagamentoCodigo' => 'UInt64',
                'administradoraCodigo' => 'UInt64',
                'financeiroCodigo' => 'UInt64',
                'turnoCodigo' => 'UInt64',
                'dataMovimento' => 'DateTime',
                'vencimento' => 'DateTime',
                'valorPagamento' => 'Decimal(18,4)',
                'taxaPercentual' => 'Decimal(18,4)',
                'nomeFormaPagamento' => 'String',
                'tipoFormaPagamento' => 'String',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(empresaCodigo, dataMovimento, formaPagamentoCodigo)',
            'partition_by' => 'toYYYYMM(dataMovimento)',
            'date_column' => 'dataMovimento',
        ],
        'caixas' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'caixaCodigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'funcionarioCodigo' => 'UInt64',
                'pdvCodigo' => 'UInt64',
                'centroCusto' => 'UInt64',
                'turnoCodigo' => 'UInt64',
                'dataMovimento' => 'DateTime',
                'abertura' => 'DateTime',
                'fechamento' => 'DateTime',
                'dataHoraAtualizacao' => 'DateTime',
                'apurado' => 'Decimal(18,4)',
                'diferenca' => 'Decimal(18,4)',
                'bloqueado' => 'UInt8',
                'consolidado' => 'UInt8',
                'fechado' => 'UInt8',
                'tipoBloqueio' => 'String',
                'tipoInclusao' => 'String',
                'turno' => 'String',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(empresaCodigo, dataMovimento, funcionarioCodigo)',
            'partition_by' => 'toYYYYMM(dataMovimento)',
            'date_column' => 'dataMovimento',
        ],
        'estoque_periodos' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'codigoProduto' => 'UInt64',
                'codigoUnidadeNegocio' => 'UInt64',
                'dataMovimento' => 'String',
                'quatidadeEstoque' => 'Decimal(18,4)',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(codigoUnidadeNegocio, codigoProduto)',
            'partition_by' => '',
            'date_column' => 'dataMovimento',
        ],
        'contas_bancarias' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'contaCodigo' => 'UInt64',
                'saldoAtual' => 'Decimal(18,4)',
                'ativo' => 'UInt8',
                'usaOfx' => 'UInt8',
                'descricao' => 'String',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(empresaCodigo)',
            'partition_by' => '',
            'date_column' => 'id',
        ],
        'produto_empresas' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'produtoCodigo' => 'UInt64',
                'produtoLmcCodigo' => 'UInt64',
                'estoquePadrao' => 'UInt64',
                'precoVenda' => 'Decimal(18,4)',
                'precoVendaB' => 'Decimal(18,4)',
                'precoVendaC' => 'Decimal(18,4)',
                'precoCusto' => 'Decimal(18,4)',
                'estoqueQtde' => 'Decimal(18,4)',
                'estoqueMin' => 'Decimal(18,4)',
                'fatorConversao' => 'Decimal(18,4)',
                'ativo' => 'UInt8',
                'ultimaAlteracao' => 'String',
                'ultimoUsuarioAlteracao' => 'String',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(empresaCodigo, produtoCodigo)',
            'partition_by' => '',
            'date_column' => 'id',
        ],
        'compras' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'compraCodigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'fornecedorCodigo' => 'UInt64',
                'cnpjCpfFornecedor' => 'String',
                'notaNumero' => 'String',
                'notaSerie' => 'String',
                'dataEntrada' => 'DateTime',
                'dataMovimento' => 'DateTime',
                'valorTotal' => 'Decimal(18,4)',
                'valorTotalProdutos' => 'Decimal(18,4)',
                'valorFrete' => 'Decimal(18,4)',
                'valorIcms' => 'Decimal(18,4)',
                'valorIcmsSt' => 'Decimal(18,4)',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(empresaCodigo, dataEntrada)',
            'partition_by' => 'toYYYYMM(dataEntrada)',
            'date_column' => 'dataEntrada',
        ],
        'compra_itens' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'compraCodigo' => 'UInt64',
                'fornecedorCodigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'produtoCodigo' => 'UInt64',
                'dataEntrada' => 'DateTime',
                'dataMovimento' => 'DateTime',
                'quantidade' => 'Decimal(18,4)',
                'precoCompra' => 'Decimal(18,4)',
                'precoCusto' => 'Decimal(18,4)',
                'totalCompra' => 'Decimal(18,4)',
                'totalCusto' => 'Decimal(18,4)',
                'valorIcms' => 'Decimal(18,4)',
                'valorPis' => 'Decimal(18,4)',
                'valorCofins' => 'Decimal(18,4)',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(empresaCodigo, dataEntrada, produtoCodigo)',
            'partition_by' => 'toYYYYMM(dataEntrada)',
            'date_column' => 'dataEntrada',
        ],
        'caixas_apresentados' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'caixaCodigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'dinheiroApurado' => 'Decimal(18,4)',
                'dinheiroApresentado' => 'Decimal(18,4)',
                'dinheiroDiferenca' => 'Decimal(18,4)',
                'cartaoApurado' => 'Decimal(18,4)',
                'cartaoApresentado' => 'Decimal(18,4)',
                'cartaoDiferenca' => 'Decimal(18,4)',
                'chequeApurado' => 'Decimal(18,4)',
                'chequeApresentado' => 'Decimal(18,4)',
                'chequeDiferenca' => 'Decimal(18,4)',
                'cartaFreteApurado' => 'Decimal(18,4)',
                'cartaFreteApresentado' => 'Decimal(18,4)',
                'cartaFreteDiferenca' => 'Decimal(18,4)',
                'notaPrazoApurado' => 'Decimal(18,4)',
                'notaPrazoApresentado' => 'Decimal(18,4)',
                'notaPrazoDiferenca' => 'Decimal(18,4)',
                'valeFunApresentado' => 'Decimal(18,4)',
                'valeFunApurado' => 'Decimal(18,4)',
                'valeFunDiferenca' => 'Decimal(18,4)',
                'consolidado' => 'UInt8',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(empresaCodigo, caixaCodigo)',
            'partition_by' => '',
            'date_column' => 'id',
        ],
        'bicos' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'bicoCodigo' => 'UInt64',
                'bicoNumero' => 'String',
                'bombaCodigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'produtoCodigo' => 'UInt64',
                'tanqueCodigo' => 'UInt64',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(empresaCodigo, bicoCodigo)',
            'partition_by' => '',
            'date_column' => 'id',
        ],
        // ── Tabelas dimensionais (lookup de nomes para JOINs no ClickHouse) ──
        'empresas' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'razao' => 'String',
                'fantasia' => 'String',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(empresaCodigo)',
            'partition_by' => '',
            'date_column' => 'id',
        ],
        'funcionarios' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'funcionarioCodigo' => 'UInt64',
                'nome' => 'String',
                'funcionarioReferencia' => 'String',
                'cpf' => 'String',
                'funcaoCodigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'ativo' => 'UInt8',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(funcionarioCodigo)',
            'partition_by' => '',
            'date_column' => 'id',
        ],
        'produtos' => [
            'columns' => [
                'id' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'produtoCodigo' => 'UInt64',
                'nome' => 'String',
                'referenciaCodigo' => 'String',
                'grupoCodigo' => 'UInt64',
                'combustivel' => 'UInt8',
                'produtoLmcCodigo' => 'UInt64',
                'tipoCombustivel' => 'String',
                'unidadeCompra' => 'String',
                'unidadeVenda' => 'String',
                'subGrupo1Codigo' => 'UInt64',
                'subGrupo2Codigo' => 'UInt64',
                'subGrupo3Codigo' => 'UInt64',
                'produtoCodigoExterno' => 'String',
                'tipoProduto' => 'String',
                'descricaoFabricante' => 'String',
                'ncm' => 'String',
                'cest' => 'String',
                'codigoAnp' => 'String',
                'produtoCodigoBarra' => 'String',
                'codigo' => 'UInt64',
                'ativo' => 'UInt8',
                'created_at' => 'DateTime',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(produtoCodigo)',
            'partition_by' => '',
            'date_column' => 'updated_at',
        ],
        'produto_grupos' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'grupoCodigo' => 'UInt64',
                'nome' => 'String',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(grupoCodigo)',
            'partition_by' => '',
            'date_column' => 'id',
        ],
        'funcionario_funcoes' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'funcaoCodigo' => 'UInt64',
                'nome' => 'String',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(funcaoCodigo)',
            'partition_by' => '',
            'date_column' => 'id',
        ],
        'formas_pagamento' => [
            'columns' => [
                'id' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'codigo' => 'UInt64',
                'formaPagamentoCodigo' => 'UInt64',
                'diasVencimento' => 'Int64',
                'nome' => 'String',
                'tipo' => 'String',
                'ultimoUsuarioAlteracao' => 'String',
                'created_at' => 'DateTime',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(formaPagamentoCodigo, empresaCodigo)',
            'partition_by' => '',
            'date_column' => 'updated_at',
        ],
        'tanques' => [
            'columns' => [
                'id' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'tanqueCodigo' => 'UInt64',
                'codigo' => 'UInt64',
                'produtoCodigo' => 'UInt64',
                'nome' => 'String',
                'capacidade' => 'Decimal(12,3)',
                'estoqueEscritural' => 'Decimal(12,3)',
                'lastro' => 'Decimal(12,3)',
                'dataHoraMedidor' => 'DateTime',
                'ultimoUsuarioAlteracao' => 'String',
                'created_at' => 'DateTime',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(tanqueCodigo, empresaCodigo)',
            'partition_by' => '',
            'date_column' => 'updated_at',
        ],
        // ── Tabelas dimensionais adicionais (lookup para JOINs no ClickHouse) ──
        'fornecedores' => [
            'columns' => [
                'id' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'fornecedorCodigo' => 'UInt64',
                'codigo' => 'UInt64',
                'fornecedorReferencia' => 'String',
                'razao' => 'String',
                'fantasia' => 'String',
                'cnpjCpf' => 'String',
                'tipoPessoa' => 'String',
                'email' => 'String',
                'telefone' => 'String',
                'celular' => 'String',
                'cidade' => 'String',
                'uf' => 'String',
                'bairro' => 'String',
                'logradouro' => 'String',
                'numero' => 'String',
                'cep' => 'String',
                'inscricaoEstadual' => 'String',
                'inscricaoMunicipal' => 'String',
                'ultimoUsuarioAlteracao' => 'String',
                'dataHoraAtualizacao' => 'DateTime',
                'created_at' => 'DateTime',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(fornecedorCodigo, empresaCodigo)',
            'partition_by' => '',
            'date_column' => 'updated_at',
        ],
        'clientes' => [
            'columns' => [
                'id' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'clienteCodigo' => 'UInt64',
                'codigo' => 'UInt64',
                'clienteReferencia' => 'String',
                'razao' => 'String',
                'fantasia' => 'String',
                'cnpjCpf' => 'String',
                'dataCadastro' => 'Date',
                'cidade' => 'String',
                'uf' => 'String',
                'bairro' => 'String',
                'logradouro' => 'String',
                'numero' => 'String',
                'cep' => 'String',
                'telefone' => 'String',
                'celular' => 'String',
                'clienteGrupoCodigo' => 'UInt64',
                'clienteCodigoExterno' => 'String',
                'bloqueado' => 'UInt8',
                'usaLimiteLitros' => 'UInt8',
                'limiteLitros' => 'Decimal(12,3)',
                'usaLimiteReais' => 'UInt8',
                'limiteReais' => 'Decimal(12,2)',
                'ultimoUsuarioAlteracao' => 'String',
                'dataHoraAtualizacao' => 'String',
                'created_at' => 'DateTime',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(clienteCodigo, empresaCodigo)',
            'partition_by' => '',
            'date_column' => 'updated_at',
        ],
        'cliente_grupos' => [
            'columns' => [
                'id' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'grupoCodigo' => 'UInt64',
                'codigo' => 'UInt64',
                'grupoCodigoExterno' => 'String',
                'descricao' => 'String',
                'usaLimiteLitros' => 'UInt8',
                'limiteLitros' => 'Decimal(12,3)',
                'usaLimiteReais' => 'UInt8',
                'limiteReais' => 'Decimal(12,2)',
                'bloqueadoFinanceiroVencido' => 'UInt8',
                'diasTolerancia' => 'Int32',
                'created_at' => 'DateTime',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(grupoCodigo, empresaCodigo)',
            'partition_by' => '',
            'date_column' => 'updated_at',
        ],
        'bombas' => [
            'columns' => [
                'id' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'bombaCodigo' => 'UInt64',
                'bombaReferencia' => 'String',
                'codigo' => 'UInt64',
                'descricao' => 'String',
                'fabricante' => 'String',
                'modelo' => 'String',
                'serie' => 'String',
                'ilha' => 'UInt64',
                'quantidadeBicos' => 'UInt64',
                'tipoMedicaoDigital' => 'UInt8',
                'created_at' => 'DateTime',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(bombaCodigo, empresaCodigo)',
            'partition_by' => '',
            'date_column' => 'updated_at',
        ],
        // ── Tabela adicional de adquirentes/cartões ──
        'administradoras' => [
            'columns' => [
                'id' => 'UInt64',
                'codigo' => 'UInt64',
                'empresaCodigo' => 'UInt64',
                'administradoraCodigo' => 'UInt64',
                'descricao' => 'String',
                'administradoraEdi' => 'String',
                'taxaTransacao' => 'Decimal(10,4)',
                'created_at' => 'DateTime',
                'updated_at' => 'DateTime',
            ],
            'order_by' => '(administradoraCodigo, empresaCodigo)',
            'partition_by' => '',
            'date_column' => 'updated_at',
        ],
    ];
}
